### PR TITLE
Fix several XSS bugs

### PR DESCRIPTION
**Pull request by Plazmaz**
I don't think this should interfere with any functionality.

### CODE REVIEW

**Comment by Jenjen1324** [comment]
Thanks,
has been uploaded to the site

**Comment by Plazmaz** [comment]
@Jenjen1324 Please see #10 ASAP.

**Comment by Plazmaz** [comment]
None of these fixes seem to be applied to the live site.

**Comment by Jenjen1324** [comment]
Sorry, wrong server. Uploaded now

**Pull request merged**
